package builder

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

const nsisTemplate = `; NSIS Installer Script generated by Hrunner Builder (hbuild)
!include "MUI2.nsh"
!include "FileFunc.nsh"

Name "{{.Name}}"
OutFile "{{.SetupExePath}}"
InstallDir "$LOCALAPPDATA\Programs\{{.SafeDirName}}"
InstallDirRegKey HKCU "Software\{{.ApplicationID}}" "InstallPath"
RequestExecutionLevel user

!define MUI_ABORTWARNING
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_RUN "$INSTDIR\{{.ExeFileName}}"
!define MUI_FINISHPAGE_RUN_TEXT "Launch {{.Name}}"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "MainSection" SEC01
    SetOutPath "$INSTDIR"
    File "{{.ExeSourcePath}}"

    ; Create Start Menu Shortcuts
    CreateDirectory "$SMPROGRAMS\{{.Name}}"
    CreateShortcut "$SMPROGRAMS\{{.Name}}\{{.Name}}.lnk" "$INSTDIR\{{.ExeFileName}}"
    CreateShortcut "$SMPROGRAMS\{{.Name}}\Uninstall {{.Name}}.lnk" "$INSTDIR\Uninstall.exe"

    ; Create Desktop Shortcut
    CreateShortcut "$DESKTOP\{{.Name}}.lnk" "$INSTDIR\{{.ExeFileName}}"

    ; Registry entries
    WriteRegStr HKCU "Software\{{.ApplicationID}}" "InstallPath" "$INSTDIR"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{{.ApplicationID}}" "DisplayName" "{{.Name}}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{{.ApplicationID}}" "UninstallString" '"$INSTDIR\Uninstall.exe"'
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{{.ApplicationID}}" "DisplayIcon" "$INSTDIR\{{.ExeFileName}}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{{.ApplicationID}}" "DisplayVersion" "{{.Version}}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{{.ApplicationID}}" "Publisher" "{{.Publisher}}"

    WriteUninstaller "$INSTDIR\Uninstall.exe"
SectionEnd

Section "Uninstall"
    ; Remove shortcuts
    Delete "$DESKTOP\{{.Name}}.lnk"
    Delete "$SMPROGRAMS\{{.Name}}\{{.Name}}.lnk"
    Delete "$SMPROGRAMS\{{.Name}}\Uninstall {{.Name}}.lnk"
    RMDir "$SMPROGRAMS\{{.Name}}"

    ; Remove files
    Delete "$INSTDIR\{{.ExeFileName}}"
    Delete "$INSTDIR\Uninstall.exe"
    RMDir "$INSTDIR"

    ; Remove registry keys
    DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{{.ApplicationID}}"
    DeleteRegKey HKCU "Software\{{.ApplicationID}}"
SectionEnd
`

type installerTemplateData struct {
	Name          string
	SafeDirName   string
	ApplicationID string
	Version       string
	Publisher     string
	ExeFileName   string
	ExeSourcePath string
	SetupExePath  string
}

// FindMakensis looks for makensis.exe on PATH or standard install locations.
func FindMakensis() string {
	if p, err := exec.LookPath("makensis.exe"); err == nil {
		return p
	}
	commonPaths := []string{
		`C:\Program Files (x86)\NSIS\makensis.exe`,
		`C:\Program Files (x86)\NSIS\Bin\makensis.exe`,
		`C:\Program Files\NSIS\makensis.exe`,
		`C:\Program Files\NSIS\Bin\makensis.exe`,
	}
	for _, cp := range commonPaths {
		if _, err := os.Stat(cp); err == nil {
			return cp
		}
	}
	return ""
}

// GenerateAppInstaller generates an NSIS installer script and compiles it if makensis is present.
func GenerateAppInstaller(cfg *BuildConfig, exePath string) (string, error) {
	absExe, err := filepath.Abs(exePath)
	if err != nil {
		return "", err
	}

	exeFileName := filepath.Base(absExe)
	baseDir := filepath.Dir(absExe)
	baseName := strings.TrimSuffix(exeFileName, filepath.Ext(exeFileName))
	setupExeName := baseName + "Setup.exe"
	setupExePath := filepath.Join(baseDir, setupExeName)
	nsiScriptPath := filepath.Join(baseDir, baseName+"_installer.nsi")

	safeDirName := strings.ReplaceAll(cfg.Name, " ", "")
	if safeDirName == "" {
		safeDirName = baseName
	}
	pub := cfg.Publisher
	if pub == "" {
		pub = "Hrunner Application"
	}

	data := installerTemplateData{
		Name:          cfg.Name,
		SafeDirName:   safeDirName,
		ApplicationID: cfg.ApplicationID,
		Version:       cfg.Version,
		Publisher:     pub,
		ExeFileName:   exeFileName,
		ExeSourcePath: absExe,
		SetupExePath:  setupExePath,
	}

	tmpl, err := template.New("nsis").Parse(nsisTemplate)
	if err != nil {
		return "", fmt.Errorf("template parse failed: %w", err)
	}

	f, err := os.Create(nsiScriptPath)
	if err != nil {
		return "", fmt.Errorf("failed to create NSIS script file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return "", fmt.Errorf("template execution failed: %w", err)
	}
	_ = f.Close()

	// Check if makensis compiler is present
	makensis := FindMakensis()
	if makensis == "" {
		return nsiScriptPath, nil // Return the generated script path
	}

	// Compile with NSIS
	cmd := exec.Command(makensis, nsiScriptPath)
	cmd.Dir = baseDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nsiScriptPath, fmt.Errorf("makensis failed: %w\nOutput: %s", err, string(out))
	}

	return setupExePath, nil
}
